# This workflow will install Python dependencies and run the unittest suite

name: Build

on:
  push:
    branches-ignore: [results]
  pull_request:

permissions:
  contents: read

env:
  GHACTIONS: ACTIVE

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # ubuntu only, to save Actions minutes (#36)
        os: [ubuntu-latest]
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: install
      run: |
        scripts/install

    - name: Run tests
      run: |
        scripts/test
